### PR TITLE
[TEST-362] Use defaultdict for report gathering

### PR DESCRIPTION
**Pull request by dsakagi**
We ran into an issue where xdist could cause tests to run interlaced
causing unexpected state for pytest-rerun. It was suggested that
using a defaultdict here could solve the problem.

See the discussion here: 
https://github.com/datarobot/DataRobot/pull/33409#issuecomment-462539429

### CODE REVIEW

**Comment by dsakagi** [comment]
@datarobot/test-auto looks like this repo doesn't have the "Needs Review" label. I'm hoping to get this change in and have a new version of `pytest-rerunfailures` get used in the DataRobot unit tests runner, so that I can then land this change in DataRobot: https://github.com/datarobot/DataRobot/pull/33409

**Comment by dsakagi** [comment]
errrr. wat?
```
14:21:12 Collecting pip==9.0.1
14:22:11   Could not find a version that satisfies the requirement pip==9.0.1 (from versions: )
14:22:11 No matching distribution found for pip==9.0.1
```
halp?

**Comment by burkestar** [comment]
jarvis test this

**Comment by burkestar** [comment]
Release as [4.1.dr7](https://artifactory.int.datarobot.com/artifactory/webapp/#/artifacts/browse/simple/General/datarobot-python-dev/pytest-rerunfailures/4.1.dr7/pytest-rerunfailures-4.1.dr7.tar.gz) in `datarobot-python-dev` Artifactory repo.

**Pull request merged**
