### PR TITLE
[DIRE-3315] junit report fix

### PR DESCRIPTION
**Pull request by oiefimenko**
Modified junit plugin for treating `rerun` status as failure. Added additional attribute to junit report with actual status.

Testing:
Local tests. Also created test job with simple testuite with predicted amount of failures:
https://ci.int.datarobot.com/job/reruns_plugin_test_TEST/3

### CODE REVIEW

**Comment by lyapun** [comment]
I can't find in your run example of test that will pass on rerun, to check how it will be stored in junit report and rerun stats. Could you update it?

Also, please execute tests with `-vvv` to better see what's going on. Thanks!

**Comment by oiefimenko** [comment]
I changed implementation according to our discussion with @lyapun. As a result we decided to not to display rerun test in final junit report and keep all rerun data in rerun stats.
For this: 
* added skipping of rerun pytes test report by junit plugin
* added testrun_report generation in all cases

As testing I added dummy tests with configurable amount of failures and performed:
1. All tests success run:
https://ci.int.datarobot.com/job/reruns_plugin_test_TEST/1
2. All failures resolved by reruns:
https://ci.int.datarobot.com/job/reruns_plugin_test_TEST/2/
3. All failures reproduced on reruns:
https://ci.int.datarobot.com/job/reruns_plugin_test_TEST/4/
4. Max reruns param skips reruns:
https://ci.int.datarobot.com/job/reruns_plugin_test_TEST/3/

**Comment by lyapun** [comment]
> All failures resolved by reruns: https://ci.int.datarobot.com/job/reruns_plugin_test_TEST/2/

Why for this case `rerun_stats.json` says `"total_failed": 2,` ? Should be `"total_failed": 0,`, right?

**Comment by oiefimenko** [comment]
@lyapun Currently it is working the same way. `"total_failed"` is amount of failures appeared during the run no matter when it happened. Final amount of failures could be calculated from  `"total_failed" - "total_resolved_by_reruns"`

**Review by lyapun — APPROVED** [review]
Ok, code of course is tricky to understand. But if it works and tested - let's move forward.

**Review by andrew-qa — APPROVED** [review]
Looks good to me.

**Comment by oiefimenko** [comment]
@andrew-qa @lyapun 
In latest approach I forgot to replace repeated code with inheritance. Should be more clear right now. Also added some comments. Latest changes tested locally

**Comment by andrew-qa** [comment]
@oiefimenko looks much easier to read now. Good job.

**Pull request merged**
